framework:
    secret: '%env(APP_SECRET)%'
    #default_locale: en
    csrf_protection: true
    #http_method_override: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        name: CRSRSESSCK_crosiercore
        # handler_id: ~
        handler_id: session.handler.native_file
        cookie_secure: true
        cookie_samesite: lax
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
        cookie_lifetime: 6048000 # 10 semanas

    #esi: true
    #fragments: true
    php_errors:
        log: true
