# config/packages/rate_limiter.yaml
framework:
  rate_limiter:
    anonymous_api:
      # use 'sliding_window' if you prefer that policy
      policy: 'sliding_window'
      limit: 3
      interval: '10 seconds'
    authenticated_api:
      policy: 'token_bucket'
      limit: 5000
      rate: { interval: '15 minutes', amount: 500 }