security:
    enable_authenticator_manager: true
    encoders:
        CrosierSource\CrosierLibBaseBundle\Entity\Security\User:
            algorithm: auto
    
    providers:
        users:
            entity:
                class: CrosierSource\CrosierLibBaseBundle\Entity\Security\User
                property: username
    
    firewalls:
        
        login:
            pattern: ^/api/login
            stateless: true
            json_login:
                check_path: /api/login
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        
        api:
            request_matcher: App\Security\ApiFirewallRequestMatcher
            pattern: ^/api
            stateless: true
            jwt: ~
        
        
        main:
            entry_point: App\Security\LoginFormAuthenticator

            lazy: false

            remember_me:
                token_provider: 'Symfony\Bridge\Doctrine\Security\RememberMe\DoctrineTokenProvider'
                name: 'CRSRRMMBRMTK'
                secure: true
                secret: "%env(APP_SECRET)%"
                lifetime: 6048000 # 10 semanas
                domain: "%env(CROSIER_MAINDOMAIN)%"
                samesite: lax
                httponly: false
                always_remember_me: true
                path: /

            custom_authenticators:
                - App\Security\LoginFormAuthenticator
                - App\Security\APIAuthenticator

            logout:
                path: logout
                success_handler: App\Security\LogoutHandler
                #invalidate_session: false

            switch_user: true

        
        

    access_control:
        - { path: ^/api/sec/user/recuperaSenha/*, roles: PUBLIC_ACCESS }
        - { path: ^/api/login, roles: PUBLIC_ACCESS }
        - { path: ^/nosec, roles: PUBLIC_ACCESS }
        - { path: ^/getCrosierAssetUrl, roles: PUBLIC_ACCESS }
        - { path: ^/getRenderCrosierWebpackScriptTags, roles: PUBLIC_ACCESS }
        - { path: ^/getRenderCrosierWebpackLinkTags, roles: PUBLIC_ACCESS }
        - { path: ^/build, roles: PUBLIC_ACCESS }
        - { path: ^/bundles, roles: PUBLIC_ACCESS }
        - { path: ^/sec/hash, roles: PUBLIC_ACCESS }
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/vsm/tdc, roles: PUBLIC_ACCESS }
        - { path: ^/vsm/cleanls, roles: PUBLIC_ACCESS }
        - { path: ^/sec/user/recuperaSenha/*, roles: PUBLIC_ACCESS }
        #- { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/, roles: IS_AUTHENTICATED_REMEMBERED }

    role_hierarchy:
        ROLE_ADMIN: ROLE_*
